### PR TITLE
Final

### PR DESCRIPTION
**Pull request by Sannan-Ijaz**

### CODE REVIEW

**Comment by Sannan-Ijaz** [comment]
Hello Felipe.. I gave just updated the code, with correct booking stuff.

**Comment by Sannan-Ijaz** [comment]
this feature should not affect any thing. I did install a library Moment, but did not use it.. so I am not sure..Otherwise, i am happy to give the demo!!!

**Comment by Sannan-Ijaz** [comment]
Also, let me know if any thing else is needed

**Review by FelipeCostaBR — COMMENTED** [review]
delete restaurant_details.html file
changed the package.json file

**Pull request merged**
